"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/app.py']
DATA_FILES = ['src/reddit_image_picker.py', 'src/app_preferences.py']
OPTIONS = {'argv_emulation': True,
            'plist': {
                'LSUIElement': True,
            },
            'packages': ['praw', 'rumps'],
            }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
